### ISSUE TITLE
Hitting tab can cause panic

### ISSUE THREAD

**Issue by errordeveloper** [michaelmacinnis/oh#22]
This is great, I've been looking for a functional alternative shell to try for a while!

Here is a small bug report.

I've tried to type `cd /<tab>` and this is what I got:
```
> oh
foo> cd /panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xa86e7]

goroutine 1 [running]:
panic(0x1f1c40, 0xc82000a140)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/michaelmacinnis/oh/pkg/ui.files.func1(0xc8203440a0, 0x9, 0x0, 0x0, 0x3fd7d8, 0xc8201dd080, 0x0, 0x0)
	/Users/ilya/Code/.gopath/src/github.com/michaelmacinnis/oh/pkg/ui/ui.go:233 +0xe7
path/filepath.walk(0xc8204a1f60, 0x7, 0x40beb8, 0xc8203f1520, 0xc8201885d8, 0x0, 0x0)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.6/libexec/src/path/filepath/path.go:370 +0x415
path/filepath.walk(0xc82047edec, 0x4, 0x40beb8, 0xc820201380, 0xc8201885d8, 0x0, 0x0)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.6/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.walk(0xc8204bab44, 0x2, 0x40beb8, 0xc820068a90, 0xc8201885d8, 0x0, 0x0)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.6/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.Walk(0xc8204bab44, 0x2, 0xc8201885d8, 0x0, 0x0)
	/Users/ilya/Library/Local/Homebrew/Cellar/go/1.6/libexec/src/path/filepath/path.go:396 +0xe1
github.com/michaelmacinnis/oh/pkg/ui.files(0xc8204bab3b, 0x1, 0x0, 0x0, 0x0)
	/Users/ilya/Code/.gopath/src/github.com/michaelmacinnis/oh/pkg/ui/ui.go:263 +0x7e7
github.com/michaelmacinnis/oh/pkg/ui.complete(0xc8204bab38, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/ilya/Code/.gopath/src/github.com/michaelmacinnis/oh/pkg/ui/ui.go:130 +0xa31
github.com/peterh/liner.(*State).tabComplete(0xc8200a4000, 0xc820188c20, 0x9, 0x9, 0xc82049e030, 0x4, 0x4, 0x4, 0x0, 0x0, ...)
	/Users/ilya/Code/.gopath/src/github.com/peterh/liner/line.go:348 +0x165
github.com/peterh/liner.(*State).PromptWithSuggestion(0xc8200a4000, 0xc8204baad0, 0x9, 0x0, 0x0, 0x4, 0x0, 0x0, 0x0, 0x0)
	/Users/ilya/Code/.gopath/src/github.com/peterh/liner/line.go:803 +0x2e00
github.com/peterh/liner.(*State).Prompt(0xc8200a4000, 0xc8204baad0, 0x9, 0x0, 0x0, 0x0, 0x0)
	/Users/ilya/Code/.gopath/src/github.com/peterh/liner/line.go:567 +0x6c
github.com/michaelmacinnis/oh/pkg/ui.(*cli).ReadString(0xc82002e028, 0x27f70a, 0x0, 0x0, 0x0, 0x0)
	/Users/ilya/Code/.gopath/src/github.com/michaelmacinnis/oh/pkg/ui/ui.go:88 +0x39b
github.com/michaelmacinnis/oh/pkg/parser.(*scanner).Lex(0xc8200aa480, 0xc8200b82c0, 0x0)
	/Users/ilya/Code/.gopath/src/github.com/michaelmacinnis/oh/pkg/parser/parser.go:112 +0x1a6
github.com/michaelmacinnis/oh/pkg/parser.yylex1(0x3fd928, 0xc8200aa480, 0xc8200b82c0, 0xc8200b82c0, 0x0)
	yaccpar:119 +0x52
github.com/michaelmacinnis/oh/pkg/parser.(*yyParserImpl).Parse(0xc8200b82c0, 0x3fd928, 0xc8200aa480, 0x0)
	yaccpar:208 +0x6307
github.com/michaelmacinnis/oh/pkg/parser.yyParse(0x3fd928, 0xc8200aa480, 0x1dcf20)
	yaccpar:153 +0x9b
github.com/michaelmacinnis/oh/pkg/parser.(*parser).Parse(0xc82002e020, 0x40bf08, 0xc82002e028, 0x3fd8f0, 0xc8200b4000, 0x22e390, 0x2, 0x27fa00, 0x40bf08)
	/Users/ilya/Code/.gopath/src/github.com/michaelmacinnis/oh/pkg/parser/parser.go:356 +0x1a6
github.com/michaelmacinnis/oh/pkg/parser.(*parser).Parse-fm(0x40bf08, 0xc82002e028, 0x3fd8f0, 0xc8200b4000, 0x22e390, 0x2, 0x27fa00, 0xc820011601)
	/Users/ilya/Code/.gopath/src/github.com/michaelmacinnis/oh/main.go:32 +0x69
github.com/michaelmacinnis/oh/pkg/task.Start(0xc82000b400, 0x3fd800, 0xc82002e028)
	/Users/ilya/Code/.gopath/src/github.com/michaelmacinnis/oh/pkg/task/task.go:1819 +0x109e
main.main()
	/Users/ilya/Code/.gopath/src/github.com/michaelmacinnis/oh/main.go:32 +0xf9
```

**Comment by michaelmacinnis** [comment]
Thanks for the bug report. The completion code is a bit of a mess. I'll have a look later today and see what I can do to clean it up and make it more robust.

**Comment by michaelmacinnis** [comment]
Try now. The completions for files in the root directory were wrong but should be fixed. Additionally, panics are handled by the completer so that rather than crashing it just returns no completions.

**Comment by errordeveloper** [comment]
Thank you!

**Comment by michaelmacinnis** [comment]
No problem. Thanks again for the bug report. Please let me know if you encounter other unexpected or erroneous behavior.
